apiVersion: apps/v1
kind: Deployment
metadata:
  name: clean_up
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  replicas: 4
  selector:
    matchLabels:
      app: clean_up
  template:
    metadata:
      labels:
        app: clean_up
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
